version: '3.9'

services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.8.12-management
    environment:
      RABBITMQ_DEFAULT_USER: user
      RABBITMQ_DEFAULT_PASS: pass
    ports:
      - "5672:5672"
      - 15672:15672
    hostname: rabbitmq-server
    volumes:
      - rabbitmqdata:/var/lib/rabbitmq

  app:
    container_name: wecharge-mqtt
    image: lexlutter/wcharge-mqtt:0.0.1
    environment:
      DISABLE_SWAGGER_HTTP_HANDLER: true
      APP_NAME: wcharge_mqtt
      APP_VERSION: 0.0.1
      LOG_LEVEL: debug
      MQTT_URL: 'amqp://user:pass@rabbitmq-server'
    ports:
      - 8080:8080
      - 9090:9090
    depends_on:
      - rabbitmq

